--- # LOOP PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh 
  tasks:
    - name: Create a list of users
      user: name={{ item }} state=present
      with_items:
        - abc
        - def
        - ghi
