--- #My FIRST PLAYBOOK
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  vars:
    playbookversion: 0.1.b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which package?
      default: telnet
  tasks:
    - name: Install apache
      yum: pkg=httpd-{{ apache_version }} state=installed
    - name: Install the Indicated package
      yum: pkg={{ pkgtoinstall }} state=present
