--- # When COnDITION PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  vars_files:
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache web server on RedHat Distribution
      action: yum name=httpd-{{apache_version }} state=installed
      when: ansible_os_family == "RedHAT" 
      notify: Restart HTTPD
    - name: Install Apache web server on Debian/Ubuntu Distribution
      action: apt-get name=httpd-{{apache_version }} state=installed
      when: ansible_os_family == "Debian" 
      notify: Restart HTTPD
  handlers:
     - name: Restart HTTPD
       action: service name=httpd state=restarted
