--- # Outline to Playbook Translation
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when the playbook starts
    raw: /usr/bin/date > /home/test/playbook_start.log
  - name: install the apache web server
    yum: pkg=httpd state=latest
  - name: start the web service
    service: name=httpd state=restarted
  - name: verify that the web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software -telnet
    yum: pkg=telnet state=latest
  - name: install client software -lynx
    yum: pkg=lynx state=latest
  - name: log all the packages install on the system
    raw: yum list installed> /home/test/installed.log
  - name: date/time stamp for when playbok ends
    raw: /usr/bin/date > /home/test/playbook_end.log
