--- # LOOP PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: test
  sudo : yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Add a list of users
      user: name={{ item }} state=present
      with_items: 
        - user1
        - user2
        - user3
