--- # START AT PLAYBAOOK EXAMPLE
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Telnet
    yum: pkg=telnet state=latest
  - name: Instrall Lynx
    yum: pkg=lynx state=latest
  - name: List HOme
    command: ls -l /home/test
    register: result
  - debug: var=result

